services:
  ups-overseerr:
    image: sctx/overseerr:latest
    hostname: ups-overseerr
    container_name: ups-overseerr
    restart: unless-stopped
    environment:
      PORT: ${OVERSEERR_PORT}
    ports:
      - ${OVERSEERR_PORT}:${OVERSEERR_PORT}
    volumes:
      - overseerr:/app/config
  
  ups-riven-frontend:
    image: spoked/riven-frontend:latest
    hostname: ups-riven-frontend
    container_name: ups-riven-frontend
    restart: unless-stopped
    environment:
      ORIGIN: ${RIVEN_ORIGIN} #Remove if behind reverse proxy
    ports:
      - ${RIVEN_PORT}:3000
    volumes:
      - frontend:/riven/config
    depends_on:
      ups-riven-backend:
        condition: service_healthy
    tty: true
    
  ups-riven-backend:
    image: spoked/riven:latest
    hostname: ups-riven-backend
    container_name: ups-riven-backend
    restart: unless-stopped
    environment:
      RIVEN_FORCE_ENV: true
      RIVEN_SYMLINK_RCLONE_PATH: ${RCLONE_MNT}/__all__
      RIVEN_SYMLINK_LIBRARY_PATH: ${LIBRARY_MNT}
      RIVEN_DATABASE_HOST: postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@${PG_HOST}/${RIVEN_DB}
      RIVEN_DOWNLOADERS_REAL_DEBRID_ENABLED: true
      RIVEN_DOWNLOADERS_REAL_DEBRID_API_KEY: ${REAL_DEBRID}
      RIVEN_CONTENT_OVERSEERR_ENABLED: true
      RIVEN_CONTENT_OVERSEERR_URL: http://ups-overseerr:${OVERSEERR_PORT}
      RIVEN_CONTENT_OVERSEERR_USE_WEBHOOK: true
      RIVEN_SCRAPING_TORRENTIO_ENABLED: true
      RIVEN_SCRAPING_ZILEAN_ENABLED: true
      RIVEN_SCRAPING_ZILEAN_URL: http://ups-zilean:8181
    volumes:
      - backend:/riven/data
      - ${ROOT_PATH}:${ROOT_PATH}
    depends_on:
      ups-plex:
        condition: service_started
      ups-database:
        condition: service_healthy
      ups-zilean:
        condition: service_healthy
    healthcheck:
      test: 'curl -s http://localhost:8080 >/dev/null || exit 1'
      interval: 30s
      timeout: 10s
      retries: 10
    tty: true
    
  ups-database:
    image: postgres:17-alpine
    hostname: ups-database
    container_name: ups-database
    restart: unless-stopped
    environment:
      PGDATA: ${PG_DATA}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${RIVEN_DB}
    volumes:
      - database:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  ups-zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest
    hostname: ups-zurg
    container_name: ups-zurg
    restart: unless-stopped
    environment:
      LOG_LEVEL: INFO
    volumes:
      - ./zurg-config.yml:/app/config.yml
      - zurg:/app/data
    healthcheck:
      test: curl -f localhost:9999/dav/version.txt || exit 1
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 5s
    
  ups-rclone:
    image: rclone/rclone:latest
    hostname: ups-rclone
    container_name: ups-rclone
    restart: unless-stopped
    volumes:
      - ${RCLONE_MNT}:/data:rshared
      - ./rclone.conf:/config/rclone/rclone.conf
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      ups-zurg:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "test -d /data/__all__"]
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 5s
    command: "mount zurg: /data --allow-other --allow-non-empty --dir-cache-time 10s --vfs-read-chunk-size 16M --vfs-read-chunk-size-limit 256M --vfs-cache-mode writes --uid ${USER_ID} --gid ${GROUP_ID} --log-level NOTICE"

  ups-zilean:
    image: ipromknight/zilean:latest
    hostname: ups-zilean
    container_name: ups-zilean
    restart: unless-stopped
    environment:
      Zilean__Database__ConnectionString: Host=${PG_HOST};Port=5432;Database=${ZILEAN_DB};Username=${PG_USER};Password=${PG_PASSWORD}
    volumes:
      - zilean:/app/data
      - zilean-tmp:/tmp
    depends_on:
      ups-database:
        condition: service_healthy
    healthcheck:
      test: curl --connect-timeout 10 --silent --show-error --fail http://localhost:8181/healthchecks/ping
      timeout: 60s
      interval: 30s
      retries: 10

  ups-plex:
    image: plexinc/pms-docker:${PLEX_TYPE}
    hostname: ups-plex
    container_name: ups-plex
    restart: unless-stopped
    environment:
      PLEX_CLAIM: ${PLEX_CLAIM_TOKEN}
      PLEX_UID: ${USER_ID}
      PLEX_GID: ${GROUP_ID}
    ports:
      - ${PLEX_PORT}:32400/tcp
    volumes:
      - plex:/config
      - /dev/shm:/transcode
      - ${ROOT_PATH}:${ROOT_PATH}:ro
    devices:
      - /dev/dri:/dev/dri #For hardware acceleration
    depends_on:
      ups-rclone:
        condition: service_healthy
        restart: true

volumes:
  overseerr:
  frontend:
  backend:
  database:
  zurg:
  zilean:
  zilean-tmp:
  plex:
